[package]
name = "spillway"
version = "0.1.0"
authors = ["mcannizzaro <MCannizzaro@appdynamics.com>"]

[dependencies]
iron = "0.5.1"
serde = "0.9.6"
router = "0.5.1"
serde_derive = "0.9.6"
serde_json = "0.9"
logger = "0.3.0"
hyper = "0.10"
log = "0.3.6"
env_logger = "0.3.5"
